### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by flashwave** [flashwave/sakura#20]
- [x] Further migrate everything into the router.
 - [x] Finish splitting up /authenticate into multiple pages.
- [x] Update all template files to use the router link generator and deprecate Sakura\Urls.
- [x] Implement proper IPv6 support.
- [x] Add most active poster in the last day.
- [x] Add recent posts.
- [x] Revamp the regular error handler.
- [x] Exclude the trash forum from statistics.
- [x] Attempt to deprecate $renderData entirely.
- [x] Make database migration system and ensure SQLite compatibility.
- [x] Rewrite the Tenshi text thing, make the benefits configurable in the template and update them to be relevant.
- [x] Implement an exception handler.
- [x] Include a standard development environment config file.
- [x] Switch from PHPMailer to Swift mailer since the latter is better documented and also appears to be more frequently updated.
- [x] Do maintenance mode and login checking through middleware.
- [x] Setup gulp for Typescript and Less.
- [x] Port styles to Less and implement BEM.
- [x] Optimise database query statements (don't do stuff that can be done in queries in php).
- [x] Create a custom bbcode parser.
- [x] Make the 404 page return HTTP 404 as well instead of HTTP 200.
- [x] Fix posting preview parsing normal html (doesn't affect the final post, but it's annoying).

**Comment by flashwave** [comment]
just going to keep updating this list with with new stuff
