### ISSUE TITLE
General todo list

### ISSUE THREAD

**Issue by flashwave** [flashwave/sakura#3]
I originally used todoist for this todo list but I'm getting pretty sick of Electron powered applications so I'm just dropped the general thing here.

- [x] Migrate all relevant functions in the Users class to the per-user User class.
 - [x] Notify when friends come online.
 - [x] Improve the online/offline status checker.
 - [x] Rewrite the Action code handler.
 - [x] Add a method to destroy all sessions of a user.
- [x] Finish the forum script.
 - [x] Reimplement the entire thing in non-static classes (>.>).
 - [x] Improve the posting methods.
 - [x] Write a proper BBcode parser.
 - [x] Implement forum permissions.
 - [x] Fix post editing.
- [x] Fix the issue where not being logged in while submitting a comment causes a PHP error.
- [x] Move the pagination in Yuuno to a universal template.
- [x] Use [this](http://php.net/manual/en/function.geoip-country-code-by-name.php) instead of CloudFlare to get the country code (probably rely on CF for fallback when this function doesn't work). 
- [x] Allow users that changed their name to something else to revert back to their original after a month (passing through the usually 90 day cool down).
- [x] Migrate all JavaScript to Typescript.
- [x] Deprecate setting the password hashing method to `nologin` in favour of the `RESTRICTED` permission flag to permaban a user.
